name: Code Analysis

on:
  push:

jobs:
  code_analysis_composer:
    timeout-minutes: 30
    if: github.event_name == 'pull_request'
    name: ${{ matrix.actions.name }} on PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.1"]

        actions:
          - name: PHPStan
            run: "composer phpstan"

          - name : Composer validate
            run : "composer validate"

    env:
      APP_NAME : "Worksome CI"
      APP_ENV : testing
      FEATURE_FLAGS_GRAPHQL_V2: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          tools: composer, cs2pr

      - name: Copy .env file
        run: cp .env.example .env


      - name: Install Composer dependencies
        uses: ramsey/composer-install@v2

      - run: ${{ matrix.actions.run }}